# Generated by Django 4.0.6 on 2022-08-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image_main',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image5',
        ),
    ]
