# Generated by Django 4.0.6 on 2022-08-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_name_car_brand_rename_image_car_image_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image5',
        ),
    ]
